version: '3.8'

services:
  backend:
    build: .
    container_name: enginuity-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: enginuity-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

